INCLUDE=-I"../wrestd/include"

# obviously this is done very poorly but who cares
19:
	$(CXX) $(INCLUDE) Day19.cpp -o day19 -std=c++14 -O2

25:
	$(CXX) $(INCLUDE) Day25.cpp -o day25 -std=c++14 -O2

23:
	$(CXX) $(INCLUDE) Day23.cpp -o day23 -std=c++14 -O2

21:
	$(CXX) $(INCLUDE) Day21.cpp -o day21 -std=c++14 -O2
